//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRCDO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public status()
        {
            this.reserve = new HashSet<reserve>();
        }
    
        public string idStatus { get; set; }
        public string status1 { get; set; }
    
        public virtual ICollection<reserve> reserve { get; set; }
    }
}
