//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRCDO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int iduser { get; set; }
        public string nickname { get; set; }
        public string pass { get; set; }
        public string idRole { get; set; }
    
        public virtual client client { get; set; }
        public virtual role role { get; set; }
    }
}
